.editorconfig, engine/_classes/class.bertagallery.php, engine/_classes/class.bertautils.php, engine/css/editor.css.php
Skip resizing of animated gif files. Use original file instead.
=> Skip resizing of animated gifs

_api_app/app/SiteSettings.php
=> JSON schema for settings

_api_app/app/Http/Controllers/SectionController.php, _api_app/app/Http/Controllers/SiteController.php, _api_app/app/Http/Controllers/StateController.php, _api_app/app/Sections.php, _api_app/app/Shared/helpers.php, _api_app/app/SiteSectionsDataService.php, _api_app/app/SiteSettings.php, _api_app/app/Sites.php, _api_app/app/Storage.php, _api_app/app/Tags.php, _api_app/composer.json, _api_app/composer.lock, sample-data/blog.[section-name].xml, sample-data/sections.xml, sample-data/settings.[template-name].xml, sample-data/settings.xml, sample-data/sites.xml, sample-data/tags.xml
Add JSON scheme to understand the XML files
specification: http://json-schema.org/specification.html
=> Initial JSON scheme and default value array

_api_app/app/Shared/Storage.php, _api_app/app/Sites/Sections/Entries/SectionEntriesDataService.php
- Added documentation string for entry data service
- Added XML example
- Added schema
=> Json schema section entries

_api_app/app/Sites/TemplateSettings/SiteTemplateSettingsDataService.php
JSON schema for SiteTemplateSettingsDataService added.
=> JSON schema and doc string for SiteTemplateSettings

_api_app/app/Configuration/SiteSettingsConfigService.php, _api_app/app/Configuration/SiteTemplatesConfigService.php, _api_app/app/Shared/I18n.php, _api_app/app/Shared/Storage.php
Update old berta references: use old berta path from config.
=> Update old berta references

_templates/default/template.tpl, _templates/mashup-0.3.5/template.tpl, _templates/messy-0.4.2/template.tpl, _templates/white-0.3.5/template.tpl
Sync site common input fields with Redux: `additionalText`, `siteFooter`, `siteHeading`, `additionalFooterText`
=> Sync site common input fields from "my site"

engine/shopsettings.php
Small fixes for shop plugin: 
- redirect to login from shop settings page
=> Sync shop plugin

engine/index.php
- It's temp fix untill we move the eidtors logic outside of iframe
=> Allow the eidtors iframe to show modals

engine/index.php
allow-forms added to sandbox rules
to fix the HTML editing form and hyperlink adding
=> Fix HTML popup from submission

editor/package-lock.json, editor/package.json, editor/src/app/app-state/app-state.interface.ts, editor/src/app/app-state/app.actions.ts, editor/src/app/app-state/app.state.ts, editor/src/app/app.component.ts, editor/src/app/app.module.ts
- Add state management to the new angular app.
- Use NGXS state library for managing state
- Add some basic actions to show how it works
=> Angular state management with NGXS

editor/src/app/sites/sections/section.component.ts, editor/src/app/sites/sections/sections-state/site-sections.state.ts, editor/src/app/sites/sections/site-sections.component.ts, editor/src/app/sites/template-settings/site-template-settings.state.ts
Adds section params in sections pane, for those sections that have them
=> Section param settings

_api_app/app/Http/Controllers/AuthController.php, _api_app/app/User/UserModel.php, editor/src/app/app-state/app-state.interface.ts, editor/src/app/app-state/app-state.service.ts, editor/src/app/app-state/app.actions.ts, editor/src/app/app-state/app.state.ts, editor/src/app/app.module.ts, editor/src/app/header/header.component.ts, editor/src/app/login/login.component.ts, editor/src/app/sites/sites.component.ts, editor/src/app/user/user-actions.ts, editor/src/app/user/user-state.ts, editor/src/app/user/user.state.model.ts
User state in app state:
- separate user object in app state
- manage login/logout actions through user state
=> User state in app state

_api_app/app/Http/Controllers/AuthController.php, _api_app/app/Http/routes.php, editor/src/app/app-routing.module.ts, editor/src/app/app-state/app-state.service.ts, editor/src/app/app.module.ts, editor/src/app/profile-dropdown/profile-dropdown.component.ts, editor/src/app/sites/settings/site-settings.component.ts, editor/src/app/sites/settings/site-settings.service.ts, editor/src/app/user/user-account.component.ts, editor/src/app/user/user.service.ts, editor/tslint.json
`Change password` component for self hosted Bertas
=> Change password

editor/package-lock.json, editor/package.json, editor/src/app/app-state/app-state.service.ts, editor/src/app/sites/sections/entries/entries-state/section-entries.actions.ts, editor/src/app/sites/sections/entries/entries-state/section-entries.state.ts, editor/src/app/sites/sections/sections-state/site-sections.actions.ts, editor/src/app/sites/sections/sections-state/site-sections.state.ts, editor/src/app/sites/sections/site-sections.component.ts, editor/src/app/sites/sections/tags/section-tags.actions.ts, editor/src/app/sites/sections/tags/section-tags.state.ts, editor/src/app/sites/settings/site-settings.actions.ts, editor/src/app/sites/settings/site-settings.state.ts, editor/src/app/sites/site.component.ts, editor/src/app/sites/sites-state/site-state.model.ts, editor/src/app/sites/sites-state/sites.actions.ts, editor/src/app/sites/sites-state/sites.state.ts, editor/src/app/sites/sites.component.ts, editor/src/app/sites/template-settings/site-template-settings.state.ts, editor/src/app/sites/template-settings/site-teplate-settings.actions.ts
=> Multisites actions

editor/src/app/shared/helpers.ts, editor/src/app/sites/sections/entries/entries-state/section-entries.actions.ts, editor/src/app/sites/sections/entries/entries-state/section-entries.state.ts, editor/src/app/sites/sections/section.component.ts, editor/src/app/sites/sections/sections-state/site-sections.actions.ts, editor/src/app/sites/sections/sections-state/site-sections.state.ts, editor/src/app/sites/sections/site-sections.component.ts, editor/src/app/sites/sections/tags/section-tags.actions.ts, editor/src/app/sites/sections/tags/section-tags.state.ts
=> Section actions

_templates/default/template.conf.php, _templates/mashup-0.3.5/template.conf.php, _templates/messy-0.4.2/template.conf.php, _templates/white-0.3.5/template.conf.php, editor/src/app/sites/shared/setting.component.ts, engine/inc.settings.php
=> Setting h4 title

editor/src/app/inputs/color-input.component.ts, editor/src/styles/_buttons.scss, editor/src/styles/_forms.scss, editor/src/styles/_variables.scss, editor/src/styles/styles.scss
- Button styles: common button, secondary, active, hover, focus, disabled.
- Add button styles to color picker buttons
=> Buttons design

editor/src/app/app-routing.module.ts, editor/src/app/sites/sections/section.component.ts, editor/src/app/sites/sections/site-sections.component.ts, editor/src/app/sites/sections/site-sections.module.ts, editor/src/styles/_sections.scss, editor/src/styles/styles.scss
=> Sections panel design

editor/src/app/inputs/inline-text-input.component.ts, editor/src/app/inputs/text-input.component.ts, editor/src/app/sites/sections/section.component.ts, editor/src/app/sites/shared/sites-shared.module.ts, editor/src/app/sites/site.component.ts, editor/src/app/sites/sites.component.ts, editor/src/styles/_aside.scss, editor/src/styles/_sites.scss, editor/src/styles/styles.scss
- Inline input component
- Use inline input component in sections panel
- Multisite panel design
=> Multisite panel design

editor/src/app/inputs/text-input.component.ts, editor/src/styles/_forms.scss
- Optional `label` attribute. 
- Optional `type` attribute, deafult is `text`. 
- Optional `placeholder` attribute.  
- Optional `enabledOnUpdate` attribute. This doesn't disable input field while saving data.
- Optional `disabled` attribute.
=> Text input improvements

editor/src/app/app.module.ts, editor/src/app/inputs/text-input.component.ts, editor/src/app/login/login.component.ts, editor/src/styles/_forms.scss, editor/src/styles/_login.scss, editor/src/styles/_variables.scss, editor/src/styles/styles.scss
=> Login component design

.gitignore, editor/src/app/app.module.ts, editor/src/app/inputs/text-input.component.ts, editor/src/app/shop/orders/shop-orders.actions.ts, editor/src/app/shop/orders/shop-orders.component.ts, editor/src/app/shop/orders/shop-orders.state.ts, editor/src/app/shop/products/shop-products.actions.ts, editor/src/app/shop/products/shop-products.component.ts, editor/src/app/shop/products/shop-products.state.ts, editor/src/app/shop/regional-costs/shop-regional-costs.actions.ts, editor/src/app/shop/regional-costs/shop-regional-costs.component.ts, editor/src/app/shop/regional-costs/shop-regional-costs.state.ts, editor/src/app/shop/settings/shop-settings-config.state.ts, editor/src/app/shop/settings/shop-settings.actions.ts, editor/src/app/shop/settings/shop-settings.component.ts, editor/src/app/shop/settings/shop-settings.state.ts, editor/src/app/shop/shop-state.service.ts, editor/src/app/shop/shop.actions.ts, editor/src/app/shop/shop.component.ts, editor/src/app/shop/shop.state.ts
-  [x] Sync shop product data
-  [x] Sync region and regional cost data
-  [x] Sync shop settings data
---
---
---
- ~~[ ] Add product on entry with product add~~ This will be done with entry sync
=> Feat shop data sync

editor/src/app/shop/products/shop-products.actions.ts, editor/src/app/shop/products/shop-products.component.ts, editor/src/app/shop/products/shop-products.state.ts
Fix: identify product by `id`, `uniqid` is a reference to entry
=> Fix: product unique id

editor/src/app/inputs/inline-text-input.component.ts, editor/src/app/inputs/text-input.component.ts, editor/src/app/shop/orders/shop-orders.component.ts, editor/src/app/shop/products/shop-products.component.ts, editor/src/app/shop/regional-costs/shop-regional-costs.component.ts, editor/src/app/shop/settings/shop-settings.component.ts, editor/src/app/shop/shop.component.ts, editor/src/styles/_aside.scss, editor/src/styles/_forms.scss, editor/src/styles/_shop.scss, editor/src/styles/styles.scss
- Product view is missing `price` field
- Order view requires more data
=> Shop panel design

editor/src/app/sites/shared/setting.component.ts, editor/src/styles/_aside.scss
=> Setting description

editor/src/app/app.component.ts, editor/src/app/sites/sections/section.component.ts, editor/src/app/sites/sections/site-sections.component.ts, editor/src/app/sites/settings/site-settings.component.ts, editor/src/app/sites/template-settings/site-template-settings.component.ts
Preserve query params (site name) when navigating
=> Preserve query params

_api_app/app/Http/Controllers/AuthController.php, _api_app/app/Http/Controllers/StateController.php, _api_app/app/Http/routes.php, _api_app/app/User/UserModel.php, editor/src/app/app-state/app-state.interface.ts, editor/src/app/app-state/app-state.service.ts, editor/src/app/app-state/app.actions.ts, editor/src/app/app-state/app.state.ts, editor/src/app/inputs/text-input.component.ts, editor/src/app/login/login.component.ts, editor/src/app/user/user.actions.ts, editor/src/app/user/user.state.ts, editor/src/styles/_buttons.scss, editor/src/styles/_login.scss, editor/src/styles/_variables.scss
Application public metadata: endpoint and state update.
=> App metadata

editor/src/app/inputs/text-input.component.ts, editor/src/app/user/user-account.component.ts, editor/src/styles/_account.scss, editor/src/styles/_buttons.scss, editor/src/styles/styles.scss
=> Profile view design

editor/src/app/app-state/app-state.service.ts, editor/src/app/app.component.ts, editor/src/app/app.module.ts, editor/src/app/error-state/error.actions.ts, editor/src/app/error-state/error.interface.ts, editor/src/app/error-state/error.state.ts, editor/src/app/login/login.component.ts, editor/src/app/popup/popup.component.ts, editor/src/app/popup/popup.interface.ts, editor/src/app/popup/popup.service.ts, editor/src/app/shop/shop-state.service.ts, editor/src/styles/_popup.scss, editor/src/styles/_variables.scss, editor/src/styles/styles.scss
- Service for handling popup messages
- A component that displays messages
* Styles: Info, Success, Error, Warning
* Timer: show popup only for a time
* Modal: Popup that can't be closed by clicking outside it
- Actions for messages - buttons with callbacks
- Ability to display components will be added later
=> Notification popup

editor/src/app/inputs/inline-text-input.component.ts, editor/src/app/inputs/select-input.component.ts, editor/src/app/inputs/text-input.component.ts
=> Fix delayed input focus

editor/src/app/app-state/app-state.interface.ts, editor/src/app/app-state/app.state.ts, editor/src/app/app.component.ts, editor/src/app/app.module.ts, editor/src/app/header/header.component.ts, editor/src/app/header/preview-toggle.component.ts, editor/src/styles/styles.scss
=> Preview toggle button

_api_app/app/Http/Controllers/AuthController.php, editor/src/app/preview/preview.component.ts, engine/_classes/class.bertasecurity.php, engine/login.php
Auto login using existing token if old Berta session expires.
=> Fix old berta session expiration

editor/src/app/sites/sections/section.component.ts, editor/src/app/sites/sections/site-sections.component.ts, editor/src/app/sites/site.component.ts, editor/src/app/sites/sites-state/sites.state.ts
Update query parameters on site/section delete/rename
=> Update query params

INSTALL/includes/check.php, INSTALL/includes/first_visit.php, INSTALL/includes/wizzard.php, _api_app/app/Http/Controllers/StateController.php, _api_app/composer.json, _templates/default/template.tpl, _templates/mashup-0.3.5/template.tpl, _templates/messy-0.4.2/template.tpl, _templates/white-0.3.5/template.tpl, editor/src/app/app-state/app-state.interface.ts, editor/src/app/app-state/app.state.ts, editor/src/app/login/login.component.ts, engine/_classes/class.bertaeditor.php, engine/_classes/class.bertatemplate.php, engine/editor/inc.editor.php, engine/ie.php, engine/inc.berta_error.php, engine/inc.head.php, engine/inc.version.php, engine/inc.version_check_and_updates.php, engine/index.php, engine/login.php, engine/logout.php, engine/mobile.php, engine/multisite.php, engine/profile.php, engine/sections.php, engine/seo.php, engine/settings.php, package.json
- Update version to `1.0.0`
- Remove `int_version`, use `version` instead
=> Remove int_version

_api_app/app/User/UserModel.php
Allow `multisite` and `shop` for trial user.
=> Fix user available features for trial user

editor/src/app/preview/preview.service.ts, editor/src/app/sites/sections/section.component.ts
=> Disable external links

editor/src/app/inputs/long-text-input.component.ts, editor/src/app/inputs/select-input.component.ts, editor/src/app/inputs/text-input.component.ts, editor/src/app/inputs/text-input.service.ts, editor/src/app/sites/shared/setting.component.ts
+ Fixed long text input update on "enter"
+ Added feature, for long-text input to update on "ctrl+enter"
+ Fixed Change After Change
=> Most of text input logics moved to text input service

editor/src/app/shop/products/shop-products.component.ts, editor/src/app/shop/products/shop-products.state.ts, editor/src/app/sites/sections/entries/entries-state/section-entries.state.ts, editor/src/app/sites/sections/sections-state/site-sections.state.ts, editor/src/app/sites/sections/tags/section-tags.state.ts, editor/src/styles/_shop.scss
=> Shop products update

.htaccess
Return 404 when directly accessing storage folder
=> Return 404 when directly accessing storage folder

_api_app/app/Shared/Storage.php, editor/src/app/app-state/app-state.service.ts, editor/src/app/shared/helpers.ts
Removes XML invalid characters from user input:
- client side
- server side
=> Remove XML invalid characters

engine/_classes/class.bertautils.php, engine/upload.php
Check for corrupted images on upload
=> Check for corrupted images

editor/src/app/user/user.state.ts
- Only use token parameter once on application load
- Make sure not to use previous token if it exists
=> Possible fix for platform login: Always log in from the token

engine/editor/inc.editor.php, engine/error/404.php
=> Fix 404 include

editor/src/app/app.module.ts, editor/src/app/login/login.component.ts, editor/src/app/shared/loading/loading.component.ts, editor/src/app/shared/shared.module.ts, editor/src/app/user/user.state.ts, editor/src/styles/_login.scss
So the user would know that something is happening during login.
=> Loading animation for login page

_api_app/.env.example, _api_app/app/Exceptions/Handler.php, _api_app/app/Http/Controllers/StateController.php, _api_app/app/Http/routes.php, _api_app/bootstrap/app.php, _api_app/composer.json, _api_app/composer.lock, _api_app/config/sentry.php, editor/package-lock.json, editor/package.json, editor/src/app/app.module.ts, editor/src/app/sentry.error-handler.ts
Ability to send Errors to Sentry if Sentry DSN is provided
=> Error handling

engine/_classes/class.bertagallery.php
Slideshow width based on widest image for all other templates. For Messy template we have special setting to enable this behaviour.
=> Slideshow width based on widest image

_api_app/app/Shared/ConfigHelpers.php, _api_app/app/Sites/Sections/SiteSectionsDataService.php, _api_app/app/Sites/Settings/SiteSettingsDataService.php
Server side - format values according to configuration for:
=> Server side: format values according to configuration

_api_app/app/Sites/Sections/SiteSectionsDataService.php
Added a comparison on the title to be able to change the title even if the name does not change
=> Fixing the section name

editor/src/app/sites/site.component.ts, editor/src/styles/_aside.scss, editor/src/styles/_sites.scss
I add a hover on the multisite link and display a background on the current site
=> Feature on the multisite display of the active site

_templates/mashup-0.3.5/mashup.js
Add a check on the variable 'source' to see if this variable is not undefined
=> Fix mashup.js undefined error

editor/src/styles/_forms.scss
Use text hover color ($grey-80) for all input text content even when they're not on hover.
Restyle toggles.
=> Toggle and text enhancements

editor/src/app/sites/sections/sections-state/site-sections.state.ts, editor/src/app/sites/sites-state/sites.state.ts
add a browser check to modify our behavior on the Sort() method if we are on Firefox or on Other
=> Fix firefox behavior on the sort method for drag and drop

_templates/_plugins/function.selectMarkedEntries.php, engine/_classes/class.berta.php, engine/_classes/class.bertatemplate.php, engine/_classes/class.clean_url.php
Checking the uptdate guide and change function that do error
=> Change code to update to 7.1 php version

_templates/default/default.js, _templates/messy-0.4.2/mess.js, _templates/white-0.3.5/white.js
Fix iframe wrapper for iframes without src
=> Fix iframe wrapper

_api_app/app/Sites/Settings/SiteSettingsDataService.php
Historically the templates had different versions in settings, but the feature was never fully implemented.
There are only one set of settings with the current version and that's it.
So we update the template version automatically.
In Future we should remove the version intirely, so we don't have this problem any more.
=> Automatically update template version in settings.xml

editor/src/app/sites/sites-state/sites.state.ts
The problem her is that the state of the section entries is never updated
=> Error creating first entry on new multisite or a cloned multisite

editor/src/app/inputs/text-input.component.ts, editor/src/app/shop/regional-costs/shop-regional-costs.component.ts, editor/src/app/sites/shared/setting-row-add.component.ts
add 3 key event on the form of the shop and of the social media to submit when the key enter is pressed
=> Submit form when enter key is pressed

_api_app/app/Sites/SitesController.php, _api_app/app/Sites/SitesDataService.php
=> Delete the shop orders of newly cloned site

_api_app/app/Shared/Storage.php
Checking if the folder -site exist in storage and if it's not here we create it
=> Fix the bug that is erupting when you clone after creating your berta site

editor/src/app/inputs/text-input.service.ts
Prevent numeric css property changes in textarea input component on up/down keypress.
=> Prevent numeric css property changes in textarea input component

_api_app/app/Dev/TestController.php, _api_app/app/Sites/Sections/Entries/Galleries/EntryGalleryRenderService.php, _api_app/app/Sites/Sections/Entries/Galleries/GalleryColumnRenderService.php, _api_app/app/Sites/Sections/Entries/Galleries/GalleryLinkRenderService.php, _api_app/app/Sites/Sections/Entries/Galleries/GalleryPileRenderService.php, _api_app/app/Sites/Sections/Entries/Galleries/GalleryRowRenderService.php, _api_app/app/Sites/Sections/Entries/Galleries/GallerySlideshowRenderService.php, _api_app/app/Sites/Sections/Entries/SectionEntriesController.php, _api_app/app/Sites/Sections/Entries/SectionEntryRenderService.php, engine/_classes/class.bertatemplate.php, engine/elements.php
=> Refactor: entry render service

_templates/messy-0.4.2/template.tpl, engine/_classes/class.bertatemplate.php
Use shopping cart render service from API
=> Twig: shopping cart

_api_app/app/Sites/Sections/SectionHeadRenderService.php, _api_app/app/User/UserModel.php
Fix: prevent Sentry script include for self hosted app
=> Fix Sentry script include

_templates/default/style.css.php, _templates/default/template.conf.php, _templates/mashup-0.3.5/style.css.php, _templates/mashup-0.3.5/template.conf.php, _templates/messy-0.4.2/style.css.php, _templates/messy-0.4.2/template.conf.php, _templates/white-0.3.5/style.css.php, _templates/white-0.3.5/template.conf.php
=> Design settings for additional text
